### ISSUE TITLE
Create keyset automatically when active keyset is checked

### ISSUE THREAD

**Issue by duggerd** [duggerd/KFDtool#13]
When a radio is keyloaded for the first time, there are no keysets. Therefore, when the active keyset option is selected (default behavior), no keysets are found and therefore the error "no active keyset" is returned.

While technically correct behavior, this isn't a great user experience. The Motorola KVLs in this situation silently use keyset ID 1.

A dialog should be shown saying that no active keyset is found, and ask the user if keyset ID 1 should be used.

**Comment by duggerd** [comment]
Silently create/use keyset 1 as having mandatory user interaction will be an issue with multiple keyload and scripted keyload.

Document this behavior in the manual.

**Comment by mattames** [comment]
This also seems to be the behaviour on KVL3000 version 2.xx as well.
